name: Update version

# on:
#   create:
#     types: [tag]
on:
  push:
    tags:
    - '*'

jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Update file and commit
        run: |
          sed -i "s#__CURRENT_VERSION__#${{ github.ref_name }}#g" versions.cfg
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "update version on tag creation"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          # ???
          force: true
          tags: true
